package elsu.common;

/**
 *
 * @author ss.dhaliwal_admin
 */
public enum StatusType {

    ABORT, ACCEPT, ACTIVATE, ADD, ALLOCATE, ALTER, APPEND,
    CANCEL, CLEAR, CHANGE, CLOSE, COMPLETE, COMPRESS, CONNECT, COPY, CREATE,
    DEACTIVATE, DEBUG, DECOMPRESS, DECRYPT, DELETE, DELIVERY, DESTROY,
    DISCONNECT, DROP,
    ENCRYPT, ERROR, EXECUTE, EXISTS, EXPAND, EXTRACT,
    FAIL, FIND, FREE,
    INFORMATION, INITIALIZE, INSERT,
    KILL,
    LISTENING,
    MESSAGE, MODIFY,
    NEW, NOTFOUND,
    OPEN,
    QUEUED,
    READ, READONLY, READWRITE, REJECT, RELEASE, REMOVE, RENAME, RESET, ROLLBACK,
    RUN,
    SELECT, SENT, SEQUENCE, SHUTDOWN, START, STOP,
    TRANSACTION, TRUNCATE,
    UPDATE,
    WRITE, WARNING
}
